application:
  logging:
    enabled: true
server:
  port: 8010
spring:
  application:
    name: attendance-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance-db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true